### ISSUE TITLE
Support more wallets

### ISSUE THREAD

**Issue by henridf** [alchemistcoin/sandwiched-frontend#7]
As of #6 we have walletconnect enabled. We should at some point add support for other wallets. This can come post-MVP.

**Comment by joenelsong** [comment]
These wallets should be very simple to implement:
1. Torus - working (doesn't need api key)
2. Formatic - can't get an api key for this.. site hangs
3. Authereum - ...
4. bitski - ...

I've never used any of them, but the wallet project we're seems to have easy support for them.

**Comment by joenelsong** [comment]
unassigning this from myself for now. My branch has very little code committed, but some notes above.
