### ISSUE TITLE
Mobile wallet connect issues

### ISSUE THREAD

**Issue by henridf** [alchemistcoin/sandwiched-frontend#77]
Field reports:

> 1. I can’t connect wallet on Brave mobile. Usually it just redirects me to Metamask but not in this case.

> 2. Can't connect wallet on chrome android 11. Oxygen OS 11.0.1.1.GM21BA Both buttons don't work, nothing happens

**Comment by henridf** [comment]
Also I tried out sandwiched.wtf on ios and connect to wallet did nothing.

**Comment by ZiggStardust** [comment]
@henridf fixed in production

**Comment by henridf** [comment]
Thanks @ZiggStardust
