### ISSUE TITLE
Enter wallet address follow-on improvements

### ISSUE THREAD

**Issue by henridf** [alchemistcoin/sandwiched-frontend#83]
The idea is to turn the wallet entry into a search bar / input box, and do away with the modal.

Also, we should have this on the results page, somewhere below the "you've been sandwiched" text.

**Comment by joenelsong** [comment]
I think the new design is like this (as I see in figma and in the discord channel)
![image](https://user-images.githubusercontent.com/7134689/122632241-67c39c80-d086-11eb-945e-70f92aa08c11.png)
