### ISSUE TITLE
Reverse ENS

### ISSUE THREAD

**Issue by henridf** [alchemistcoin/sandwiched-frontend#89]
For all displayed addresses, we should check to see if there's an associated ENS name and if so display that. 

Filing this in frontend as it's more of a presentation layer thing, but could also be done in backend if there's a strong reason for that.

**Comment by joenelsong** [comment]
https://docs.ens.domains/dapp-developer-guide/resolving-names

**Comment by joenelsong** [comment]
wechseln.eth - contains 1 sandwich
grantland.eth - contains 0 sandwiches
